apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocker-full-suite
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      mocker: web
  template:
    metadata:
      labels:
        mocker: web
    spec:
      containers:
        - name: mocker
          image: mocker:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mocker-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    mocker: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
